version: '3'

services:
  #openjdk:
  #  build:
  #    context: ./
  #    dockerfile: ./docker/openjdk/Dockerfile
  mongo:
    build:
      context: ./
      dockerfile: ./docker/mongo/Dockerfile
    ports:
      - "27017:27017"